unicorn-objs := unicorn-i2c.o unicorn-video.o unicorn-core.o unicorn-ioctlops.o unicorn-fops.o unicorn-vbuff.o unicorn-spi-flash.o unicorn-resource.o unicorn-mmap.o
obj-$(CONFIG_AL_UNICORN) += unicorn.o
