obj-$(CONFIG_AL_UNICORN) += unicorn.o
unicorn-y := unicorn-core.o unicorn-i2c.o unicorn-spi-flash.o
unicorn-$(CONFIG_AL_UNICORN_WIDTH_VIDEO_SUPPORT) += unicorn-fops.o \
	unicorn-ioctlops.o unicorn-video.o unicorn-vbuff.o unicorn-mmap.o \
	unicorn-resource.o
