#
# Makefile for the Linux Wireless network device drivers.
#

obj-$(CONFIG_USB_NET_COMPAT_RNDIS_WLAN)	+= rndis_wlan.o

obj-$(CONFIG_RT2X00)	+= rt2x00/
obj-$(CONFIG_ATH_COMMON)	+= ath/

obj-$(CONFIG_MAC80211_HWSIM)	+= mac80211_hwsim.o

